### ISSUE TITLE
You could you do one for PKC addon ? 

### ISSUE THREAD

**Issue by alazabe** [notsatan/kodi-strm#142]
This is something else i know , 
I did ask before the Dev of PKC addon to support strm exports so it can work with others addons and not miss with KODI DB ! 
but there no interest !

so i am here to ask if you can do it ?

**Comment by notsatan** [comment]
I've stopped using Kodi for quite a while now - I'm simply maintaining/updating this repository for anyone who may be using it. There is no plan to add new features in the near future
