### ISSUE TITLE
Create STRM without file extensions and download artwork, NFO videos/folder?

### ISSUE THREAD

**Issue by luhanmcs** [notsatan/kodi-strm#156]
Add an option to choose to remove extension to STRM or download artwork from videos. Thanks.
![fileextension](https://user-images.githubusercontent.com/22850716/132928755-a4349baa-8788-41a5-b49c-4d4ec2629086.jpg)
![nfo](https://user-images.githubusercontent.com/22850716/132928759-92027ee1-b291-423d-abed-c68d5f4729c0.jpg)

**Comment by notsatan** [comment]
I'll break this down into two parts

> - Add an option to remove extension *from* STRM

While this can easily be achieved, I find this to be pointless. If you don't need the file extensions, can't you just ignore them? I don't see this as an "*essential requirement*" - it's more of a *nice-to-have*

I don't really see any point in adding *another* flag for something this small - regardless I'll give some thought to this before making a final decision. I don't want to go about adding hundreds of flags for minor stuff. 

In the meanwhile, you can use simple regex pattern(s) (`re.sub(r'^(.*)\..*\.(.*)$', r'\1.\2', file)` maybe?) or something else to remove extensions from the generated STRM files

---

> - Add an option to download artwork from videos

This is would be a straight no. My *only* purpose behind this script (and repo as a whole) was to ***supplement*** the functionality of the Google Drive Add-on, as such I don't plan on increasing the scope of this project at the moment. 

This project will simply generate STRM files which can then be used by the add-on, reducing the wait-time.

**Comment by luhanmcs** [comment]
When the STRMs are named like this: Series - s01e01.mkv.strm the series - s01e01.NFO are not recognized together with the STRM files, I believe it is a limitation of the KODI itself.

**Comment by notsatan** [comment]
The original plan was to include this feature in the `refactor` branch (which would also include a complete refactor of the script) -- but, on second thought, working on this feature individually would be more efficient. Should be done with this in a little while

**Comment by notsatan** [comment]
@luhanmcs that should be what you wanted for your use case. Simply pull the latest version of the `master` branch, and you should be able to use the `--no-ext` flag to strip extensions from the strm files generated by `kodi-strm`. You can read the linked PR for more info on this
 - GH-215

P.S. The PR mentions this as well - the addition of the `--no-ext` flag has not been mentioned in the readme. Once I'm done with the refactor, I'll be updating the readme (with this flag as well), and creating a new release!
