### ISSUE TITLE
goindex strm generator suport

### ISSUE THREAD

**Issue by crackerbad** [notsatan/kodi-strm#315]
**Is your feature request related to a problem? Please describe.**
it would be nice if was added support to generate strm files for goindex

**Describe the solution you'd like**
goindex is simple and easy to use, it would be very good to use in kodi or other applications, but generating strm files manually is so bad, that's why I wish it had this function.

**Describe alternatives you've considered**
If it is not possible to implement this I would at least like you to help me in a way to generate the strm even if it is from a notepad with all direct links

**Additional context**
goindex https://github.com/alx-xlx/goindex
goindex exemples
https://goindex-classic.teamsdrives.workers.dev/
https://goindex.teamsdrives.workers.dev/0:/

**Comment by notsatan** [comment]
Hi, I have no plans to extend the scope for *kodi-strm* beyond what I originally intended it to be — a simple Python script to supplement an existing Kodi add-on. In line with the spirit of open source, I encourage you to fork this repo and implement the changes you need in your fork :)

> If it is not possible to implement this I would at least like you to help me in a way to generate the strm even if it is from a notepad with all direct links

The [`file_handler.py`](../blob/master/kodi_strm/file_handler.py) deals with exactly this — feel free to take a look at the source code to get an idea of what happens behind the scenes!

**Comment by notsatan** [comment]
As mentioned — I have no plans to work on this, marking this as `wontfix` and closing the issue. If you run into issues with the use of *kodi-strm*, feel free to revert back with a [new issue](../issues/new/choose)!

**Comment by crackerbad** [comment]
> Hi, I have no plans to extend the scope for _kodi-strm_ beyond what I originally intended it to be — a simple Python script to supplement an existing Kodi add-on. In line with the spirit of open source, I encourage you to fork this repo and implement the changes you need in your fork :)
> 
> > If it is not possible to implement this I would at least like you to help me in a way to generate the strm even if it is from a notepad with all direct links
> 
> The [`file_handler.py`](../blob/master/kodi_strm/file_handler.py) deals with exactly this — feel free to take a look at the source code to get an idea of what happens behind the scenes!

Thanks. But I found another script that is better for my purpose.

Anyway thanks for the reply.
