### ISSUE TITLE
QUESTION 

### ISSUE THREAD

**Issue by Fakeabhijeet** [notsatan/kodi-strm#318]
I can we you this on Android TV / Mobile..?

**Comment by notsatan** [comment]
This sounds like a query related to #84 - you might want to take a look over there.

Basically, the script can run on any platform as long it supports Python 3! Or you can generate the `strm` files from a PC and move them to the desired location as needed!

**Comment by notsatan** [comment]
Closing this issue since there's no real way to expand support for `kodi-strm` on platforms that do not have Python3 — and for platforms that do, *kodi-strm* should run fine in its current form
